#!/bin/sh

CUDA_VERSION=10.1
CUDNN_VERSION=8
PYTHON_VERSION=3.6
PYTORCH_VERSION=1.7.0+cu101


TAG=hczhu/pytorch:pytorch${PYTORCH_VERSION}-cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}-py${PYTHON_VERSION}-ubuntu18.04-runtime
TAG=`echo $TAG | tr -d '+'`


DOCKER_BUILDKIT=1 docker build \
    -t $TAG \
    --build-arg CUDA_VERSION=${CUDA_VERSION} \
    --build-arg CUDNN_VERSION=${CUDNN_VERSION} \
    --build-arg PYTHON_VERSION=${PYTHON_VERSION} \
    --build-arg PYTORCH_VERSION=${PYTORCH_VERSION} .

docker push ${TAG}
docker tag ${TAG} hczhu/pytorch:latest
