#!/bin/sh

CUDA_VERSION=11.1.1
CUDNN_VERSION=8
PYTHON_VERSION=3.8
PYTORCH_VERSION=1.8.0+cu111
APEX_COMMIT=a78ccf0b3e3f7130b3f157732dc8e8e651389922


TAG=hczhu/pytorch:pytorch${PYTORCH_VERSION}-cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}-py${PYTHON_VERSION}-ubuntu20.04-runtime
TAG=`echo $TAG | tr -d '+'`


DOCKER_BUILDKIT=1 docker build \
    -t $TAG \
    --build-arg CUDA_VERSION=${CUDA_VERSION} \
    --build-arg CUDNN_VERSION=${CUDNN_VERSION} \
    --build-arg PYTHON_VERSION=${PYTHON_VERSION} \
    --build-arg APEX_COMMIT=${APEX_COMMIT} \
    --build-arg PYTORCH_VERSION=${PYTORCH_VERSION} .

docker push ${TAG}
docker tag ${TAG} hczhu/pytorch:latest
