#!/bin/sh

TRANSFORMERS=3.1.0
DATASETS=1.0.2
LIGHTNING=0.9.0
HYDRA=1.0.2

TAG=hczhu/nlp:transformers${TRANSFORMERS}-datasets${DATASETS}-pl${LIGHTNING}-hydra${HYDRA}

DOCKER_BUILDKIT=1 docker build \
    -t $TAG \
    --build-arg TRANSFORMERS=${TRANSFORMERS} \
    --build-arg DATASETS=${DATASETS} \
    --build-arg LIGHTNING=${LIGHTNING} \
    --build-arg HYDRA=${HYDRA} .

docker push ${TAG}
docker tag ${TAG} hczhu/nlp:latest
