#!/bin/sh

TRANSFORMERS=2.11.0
NLP=0.3.0
LIGHTNING=0.9.0
HYDRA=0.11.3
DGL=0.4.3.post2

TAG=hczhu/nlp:nlp${NLP}-transformers${TRANSFORMERS}-pl${LIGHTNING}-hydra${HYDRA}-dgl${DGL}

DOCKER_BUILDKIT=1 docker build \
    -t $TAG \
    --build-arg TRANSFORMERS=${TRANSFORMERS} \
    --build-arg NLP=${NLP} \
    --build-arg LIGHTNING=${LIGHTNING} \
    --build-arg HYDRA=${HYDRA} \
    --build-arg DGL=${DGL} .

docker push ${TAG}
docker tag ${TAG} hczhu/nlp:latest