#!/bin/sh

BASE_REPO=hczhu/nlp
BASE_TAG=20201126
TAG=hczhu/summarization:${BASE_TAG}

DOCKER_BUILDKIT=1 docker build -t $TAG --build-arg BASE=${BASE_REPO}:${BASE_TAG} .

docker push ${TAG}
docker tag ${TAG} hczhu/summarization:latest
